from main import *
import upload

def lambda_handler(event, context):
    credentials = load_credentials()
    session = CaesarAPI(API_PATH, credentials)
    parser = CaesarParser()
    print("Education and Courses")
    education = get_parsed_education(session, parser)
    upload.json_file("education.json", education)    
    print("Competences")
    competences = get_parsed_competences(session, parser)
    upload.json_file("competences.json", competences)
    print("Databases")
    databases = get_parsed_databases(session, parser)
    upload.json_file("databases.json", databases)
    print("Activities")
    activities = get_parsed_activities(session, parser)
    upload.json_file("activities.json", activities)
    print("Experiences")
    experiences = get_parsed_experiences(session, parser)
    upload.json_file("experiences.json", experiences)
    print("OS")
    os = get_parsed_os(session, parser)
    upload.json_file("os.json", os)
    print("Packages")
    packages = get_parsed_packages(session, parser)
    upload.json_file("packages.json", packages)
    print("Technologies")
    technologies = get_parsed_technologies(session, parser)
    upload.json_file("technologies.json", technologies)
    print("Methods")
    methods = get_parsed_methods(session, parser)
    upload.json_file("methods.json", methods)
    print("Development")
    development = get_parsed_development(session, parser)
    upload.json_file("development.json", development)
    print("Motivation")
    motivation = get_parsed_motivation(session, parser)
    upload.json_file("motivation.json", motivation)
    document = get_latest_document(session, parser)
    print(f"item: {document}")
    resume_name, resume = session.download_document(document['Serial no.'])
    upload.binary_file("resume.docx", resume)
    print("Done")
    return {"statusCode": 200}
