name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: copy python files
      run: |
        mkdir dist
        cp *.{py,txt} dist
    - name: install AWS lambda requirements
      run: |
        pip install -r requirements_aws.txt --target dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ResumeLambda
        path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: ResumeLambda
        path: ./dist
    - name: Zip for deployment
      run: |
        mkdir deploy
        zip -r deploy/lambda.zip dist
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}          
    - name: Upload to S3
      run: |
        aws s3 sync ./deploy s3://${{ secrets.AWS_BUCKET }} --delete
