name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: copy python files
      run: |
        mkdir dist
        cp *.{py,txt} dist
    - name: install AWS lambda requirements
      run: |
        pip install -r requirements_aws.txt --target dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ResumeLambda
        path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: ResumeLambda
        path: dist
        
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl bucket-owner-full-control --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1
        SOURCE_DIR: ./dist
