name: Zip project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: copy python files
      run: |
        mkdir dist
        cp *.{py,txt} dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: caesarResume
        path: dist
